// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 917 02/14/2023)
// Created on Fri Mar 22 14:21:25 2024

adder_4bit adder_4bit_inst
(
	.X3(X3_sig) ,	// input  X3_sig
	.Y3(Y3_sig) ,	// input  Y3_sig
	.X2(X2_sig) ,	// input  X2_sig
	.Y2(Y2_sig) ,	// input  Y2_sig
	.X1(X1_sig) ,	// input  X1_sig
	.Y1(Y1_sig) ,	// input  Y1_sig
	.X0(X0_sig) ,	// input  X0_sig
	.Y0(Y0_sig) ,	// input  Y0_sig
	.Cout(Cout_sig) ,	// output  Cout_sig
	.S3(S3_sig) ,	// output  S3_sig
	.S2(S2_sig) ,	// output  S2_sig
	.S1(S1_sig) ,	// output  S1_sig
	.S0(S0_sig) 	// output  S0_sig
);

